// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.DataAccess;

#nullable disable

namespace WebApplication.Migrations
{
    [DbContext(typeof(MockContext))]
    [Migration("20230101220644_InitalCreate")]
    partial class InitalCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("WebAPI.Model.MockModel", b =>
                {
                    b.Property<string>("ValueOne")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValueTwo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ValueOne");

                    b.ToTable("MockModels");
                });

            modelBuilder.Entity("WebAPI.Model.MockModelThree", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("MockModelValueOne")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.HasIndex("MockModelValueOne");

                    b.ToTable("MockModelThrees");
                });

            modelBuilder.Entity("WebAPI.Model.MockModelThree", b =>
                {
                    b.HasOne("WebAPI.Model.MockModel", null)
                        .WithMany("Collection")
                        .HasForeignKey("MockModelValueOne")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebAPI.Model.MockModel", b =>
                {
                    b.Navigation("Collection");
                });
#pragma warning restore 612, 618
        }
    }
}
